### ISSUE TITLE
Non-Blocking Network Switch part#

### ISSUE THREAD

**Issue by sryanr** [VCL3D/VolumetricCapture#19]
Hello, I recently purchased 4 azure kinects and have been purchasing the required hardware to begin testing your volumetric capture system (workstation, NUCs, mount, etc). I am having trouble identifying a non-blocking network switch as 'non-blocking' has not been listed in the tech specs or easily recognized in google or marketplace search. Can you provide the part number for the Cisco switch you are using?  

Also, if you collected links for products you recommend you could probably make some research money from Amazon's affiliate program https://affiliate-program.amazon.com/  

Thanks for the great documentation!
Ryan

**Comment by zuru** [comment]
Hi Ryan,

the switch we use is: [CISCO SG110-16-EU 16-Port Gigabit L2 Switch](https://www.cisco.com/c/en/us/support/switches/sg100-16-16-port-gigabit-switch/model.html).

Regarding the non-blocking part, it basically means that the switch can handle all ports on full capacity simultaneously. Or otherwise, that for a 16 port switch, it has 32Gbps backplane bandwidth, i.e. all ports with deduplexed downlink/uplink can run at full traffic. More information at [link1](https://howdoesinternetwork.com/2015/what-is-a-non-blocking-switch) and [link2](https://i.cs.hku.hk/~atctam/phdthesis/node25.html).

Nonetheless, it is probably not documented anywhere as most if not all switches probably support it now. It is also not a strict requirement, but it may be helpful in situations where multiple sensors stream at higher resolutions.

Thanks for the Amazon tip, will check it out ;)

P.S. The K4A release was done hastily before lockdown, and unfortunately, there will be limited support till we can access our lab/infrastructure again.
