### ISSUE TITLE
Device_repository.exe cannot find device_respository.json

### ISSUE THREAD

**Issue by tylergibson** [VCL3D/VolumetricCapture#21]
![image](https://user-images.githubusercontent.com/1085397/80328061-0e017280-87f3-11ea-9faa-711461267b29.png)

Have spent an hour trying every combination imaginable to provide it a path.  No matter what is provided, a FATAL error results.  Simply copied the default device_repository.json to this directory.

**Comment by zokin** [comment]
Hi Tyler, can you please attach the file (`device_repository.json`)?

**Comment by xudi1227** [comment]
Hi @zokin  I also got the same problem using Azure Kinect. And here is my json file
[device_repository.zip](https://github.com/VCL3D/VolumetricCapture/files/4562005/device_repository.zip)

![KA4](https://user-images.githubusercontent.com/6670126/80771696-cda14c00-8b86-11ea-8811-28e1b766c640.png)

Basically I changed the Serial and Firmware to my own kinect specs as below.  
![Screenshot_20200501083705](https://user-images.githubusercontent.com/6670126/80771748-f88ba000-8b86-11ea-8df0-915f0d5f3dbd.png)

But still I can't add or list any Kinect using device_repository.exe. Not sure if I made any mistakes here.please let me know if someone solved this.

**Comment by xudi1227** [comment]
Btw here is my command window
![image](https://user-images.githubusercontent.com/6670126/80772158-5371c700-8b88-11ea-87a3-c6f8953236b1.png)

**Comment by zokin** [comment]
Hi Johnny,

it seems that you are missing the `-c 0` or `--cam_type 0` argument when calling the `device_repository.exe` tool.

As the help also indicates, these are needed to disambiguate between the sensors.

The documentation about this is missing, but will be added/improved the coming days as well.

Thanks for your time and help in pinpointing issues.

**Comment by tofis** [comment]
Hello all,

Another important missing point of the the [K4A alpha version](https://github.com/VCL3D/VolumetricCapture/releases/tag/4.0.1) is related to the new shaders for the K4A point cloud visualization which causes a crash. Please, find attached the missing shaders and place them in the "Resources" folder.

Sorry for the inconvenience but this release was not tested enough due to the sudden lock-down, as we have already said. Since we are coming back probably next week, we are going to fix the identified issues asap.

Thank you for your time. 
  
[depth_cloud_k4a_shaders.zip](https://github.com/VCL3D/VolumetricCapture/files/4564762/depth_cloud_k4a_shaders.zip)

**Comment by tylergibson** [comment]
> Hi Johnny,
> 
> it seems that you are missing the `-c 0` or `--cam_type 0` argument when calling the `device_repository.exe` tool.
> 
> As the help also indicates, these are needed to disambiguate between the sensors.
> 
> The documentation about this is missing, but will be added/improved the coming days as well.
> 
> Thanks for your time and help in pinpointing issues.

This isn't possible, because as @xudi1227 also points out, the device_repository.exe tool always fails due to not locating the json file.  So we can't run it.  I also attempted to manually add my Kinects to the json file as @xudi1227 did, with no success.

Having a source release would make it much easier for us to debug and provide improvements ;)

**Comment by tofis** [comment]
For the ones who use the new K4A alpha version, the recommended steps with respect to the correct usage of device_repository tool are given below:

- Assuming that there is no K4A device appropriately added in the "device_repository.json", delete any existing "device_repository.json" you copied in the root folder of the device_repository tool from other version or other folder, in order to make it clean from scratch.
- Place in the root folder of the device_repository tool the "depthengine_2_0.dll" which is missing (you can copy it from "remote_eye\bin" folder).
- Connect the first K4A device on a USB3 port (ensure that the device has been detected and runs properly, for instance using the MS Official K4A viewer).
- Run the "device_repository.exe" in the cmd using these arguments `device_repository.exe --add {device_name_prefer} --cam_type 0`.
- After that you are going to see the log you see in the screenshot below, while a new "device_repository.json" is going to be created. 
![image](https://user-images.githubusercontent.com/9459499/80862869-ff96d900-8c80-11ea-84db-8a9556de78b7.png)
- Then, running  `device_repository.exe --list`, you are going to see your device listed if everything has been completed correctly.
![image](https://user-images.githubusercontent.com/9459499/80862779-4cc67b00-8c80-11ea-91f0-f374a6f86811.png)
I hope that it will work for you. As said, we hope at the end of the next week to have an actual release with documentation.

**Comment by zuru** [comment]
Updated [documentation](https://vcl3d.github.io/VolumetricCapture/docs/configure/#creating-a-device-repository) with respect to the device repository is now available.
