### ISSUE TITLE
Intel RealSense D415 fails to start stream

### ISSUE THREAD

**Issue by GuilhermeMEESantos** [VCL3D/VolumetricCapture#69]
Good afternoon. 

I have been having problems with the intel camera not starting the stream.

![imagem](https://user-images.githubusercontent.com/94906816/145038453-e7b47ba0-4590-450c-9da1-72cb66454d61.png)

I read on [here](https://github.com/VCL3D/VolumetricCapture/issues/17#issuecomment-611647145) that maybe it could be a case of firmware (I have updated both in the camera and on the repository JSON file) or by simply disconnecting and connecting the USB cable in different USB entrances of the NUC but the error still persists. 

My setup: I have an Intel D415 camera connected to a NUC which in turn is connected to my pc via Ethernet. There is communication between the NUC and my pc but it continues saying "Unknown device stream (Color-Depth) when creating a frame source" and "No frames received, resetting device hardware".

I even tried to figure out if it could be a problem with the camera but when I used the intel viewer the stream worked. 
Any additional steps I could do to try and solve this issue?

**Comment by bhargavbompalli** [comment]
Hi, I had the exact same issue as you, and tried everything mentioned in the previous threads but nothing seemed to work.

I eventually figured out the issue was with the firmware of each of my D415 cameras. They all had the latest update (version 5.13.0.50, I believe), and in the wiki, the authors mention that they used version 5.11.15.00. This is mentioned in the "Software Setup" section.

I downgraded the firmware version for all of the cameras to 5.11.15.00 using Intel's firmware releases doc: https://dev.intelrealsense.com/docs/firmware-releases. I just changed the firmware through the RealSense Viewer program.

After downgrading, all of the cameras worked fine!

Hope this helps!
