### ISSUE TITLE
Reduction of error during calibration

### ISSUE THREAD

**Issue by dbrice01** [VCL3D/VolumetricCapture#83]
I've attempted running the calibration in different environments, with 4 cameras in different positions and so far I have not been able to reduce the size of the errors, resulting in poor camera alignment and transforms. The cameras have been setup following the instructions at: https://vcl3d.github.io/VolumetricCapture/docs/calibration/process/ 

Due to there being no availability of the IKEA JÄTTENE boxes we have laser cut and assembled MDF boxes of identical proportions, could this be the issue? Otherwise are there any suggestions for achieving a more successful calibration?

![Calibration with Noise Pattern](https://user-images.githubusercontent.com/81298532/186638278-090600a9-1d4c-452e-97ac-2c8abccb034d.PNG)
![Calibration large errors](https://user-images.githubusercontent.com/81298532/186638283-7679f2e9-64b0-4cb9-a38d-b4384ac2e741.PNG)

Many Thanks,
Daniel

**Comment by zuru** [comment]
Can you please try to rotate the boxes in the opposite direction when assembling the structure and see if that works?
I think that compared to the views depicted in the videos in this [page](https://vcl3d.github.io/VolumetricCapture/docs/acquisition/) the assembly process is not consistent with the instructions [here](https://vcl3d.github.io/VolumetricCapture/docs/calibration/assembly/).

**Comment by dbrice01** [comment]
That's exactly what my problem was, thank you for your observation. The calibration errors are now at a suitable level.

**Comment by zuru** [comment]
One more thing, when packaging the IKEA boxes, the resulting dimensions are typically not the ones reported by the IKEA website. Since you are manufacturing a replica, you should take that into account, and measure the dimensions of the `/Data/Executables/Calibration/multisensor_calibration/Resources/data/subsampled_asymmetric_structure_corrected.ply` which we updated to be in line with the assembled dimensions, and create your replica according to them. This will additionally improve accuracy.

**Comment by dbrice01** [comment]
Thank you for your advice. I have not been able to find a precise way to measure the dimensions of the structure from the .PLY file, but will continue to look into it.

**Comment by ankarako** [comment]
Hi, you can use meshlab's measuring tool
